<a href="https://colab.research.google.com/github/PhaniKris/Python/blob/main/Numpy_101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#NUMPY - Numpy is an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, 
#sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and 
#much more...

In [ ]:
#assigning value to a variable
a=21

In [ ]:
a

21

In [ ]:
b=32

In [ ]:
b

32

In [ ]:
a+b

53

In [ ]:
c=44

In [ ]:
c

44

In [ ]:
#to know the version of package installed/to check required package installed or not
! pip show numpy

Name: numpy
Version: 1.19.5
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /usr/local/lib/python3.7/dist-packages
Requires: 
Required-by: yellowbrick, xgboost, xarray, wordcloud, torchvision, torchtext, tifffile, thinc, Theano-PyMC, tensorflow, tensorflow-probability, tensorflow-hub, tensorflow-datasets, tensorboard, tables, statsmodels, spacy, sklearn-pandas, seaborn, scs, scipy, scikit-learn, resampy, qdldl, PyWavelets, python-louvain, pystan, pysndfile, pymc3, pyerfa, pyemd, pyarrow, plotnine, patsy, pandas, osqp, opt-einsum, opencv-python, opencv-contrib-python, numexpr, numba, nibabel, netCDF4, moviepy, mlxtend, mizani, missingno, matplotlib, matplotlib-venn, lightgbm, librosa, Keras, Keras-Preprocessing, kapre, jpeg4py, jaxlib, jax, imgaug, imbalanced-learn, imageio, hyperopt, holoviews, h5py, gym, gensim, folium, fix-yahoo-finance, fbprophet, f

In [ ]:
#to update installed package to the latest version
! pip install --upgrade numpy

     |████████████████████████████████| 15.3MB 190kB/s 
ERROR: tensorflow 2.5.0 has requirement numpy~=1.19.2, but you'll have numpy 1.20.3 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.
  Found existing installation: numpy 1.19.5
    Uninstalling numpy-1.19.5:
      Successfully uninstalled numpy-1.19.5


In [ ]:
! pip show numpy

Name: numpy
Version: 1.20.3
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /usr/local/lib/python3.7/dist-packages
Requires: 
Required-by: yellowbrick, xgboost, xarray, wordcloud, torchvision, torchtext, tifffile, thinc, Theano-PyMC, tensorflow, tensorflow-probability, tensorflow-hub, tensorflow-datasets, tensorboard, tables, statsmodels, spacy, sklearn-pandas, seaborn, scs, scipy, scikit-learn, resampy, qdldl, PyWavelets, python-louvain, pystan, pysndfile, pymc3, pyerfa, pyemd, pyarrow, plotnine, patsy, pandas, osqp, opt-einsum, opencv-python, opencv-contrib-python, numexpr, numba, nibabel, netCDF4, moviepy, mlxtend, mizani, missingno, matplotlib, matplotlib-venn, lightgbm, librosa, Keras, Keras-Preprocessing, kapre, jpeg4py, jaxlib, jax, imgaug, imbalanced-learn, imageio, hyperopt, holoviews, h5py, gym, gensim, folium, fix-yahoo-finance, fbprophet, f

In [ ]:
#assigning list of values to variable
a = [1, 2, 3, 4, 5]

In [ ]:
a

[1, 2, 3, 4, 5]

In [ ]:
a * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
a

[1, 2, 3, 4, 5]

In [ ]:
list1 = a

In [ ]:
list1

[1, 2, 3, 4, 5]

In [ ]:
#to know the variable data type
type(list1)

list

In [ ]:
type(a)

list

In [ ]:
import numpy as np
arr1 = np.array(list1)

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
arr1*2

array([ 2,  4,  6,  8, 10])

In [ ]:
arr1.min()

1

In [ ]:
arr1.max()

5

In [ ]:
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr1=arr1*2

In [ ]:
arr1

array([ 2,  4,  6,  8, 10])

In [ ]:
arr1.min()

2

In [ ]:
arr1.max()

10

In [ ]:
#prints zeros in 3 rows x 2 columns matrix format with data type as float
ar2=np.zeros((3,2))

In [ ]:
ar2

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
#prints values in 3 rows x 2 columns matrix format with data type as integer
ar2=np.zeros(shape=(3,2), dtype=int)+2

In [ ]:
ar2

array([[2, 2],
       [2, 2],
       [2, 2]])

In [ ]:
ar3=np.zeros(shape=(3,2), dtype=int)+4

In [ ]:
ar3

array([[4, 4],
       [4, 4],
       [4, 4]])

In [ ]:
(ar2+ar3)*6+2

array([[38, 38],
       [38, 38],
       [38, 38]])

In [ ]:
#generating random numbers from smallest valu 4 to biggest value 16 in 4 rows x 4 columns matrix format
a1=np.random.randint(low=4, high=16, size=(4,4))

In [ ]:
a1

array([[ 5, 14,  9,  4],
       [ 4,  6,  5, 13],
       [11, 15, 11,  9],
       [ 5,  9,  5,  9]])

In [ ]:
a1.max()

15

In [ ]:
a1.min()

4

In [ ]:
#to display float values
a2=np.random.randn(9)

In [ ]:
a2

array([-0.55996697,  0.35691587,  0.48404154, -0.94265819,  0.70708361,
        1.71156204, -0.7393979 , -0.35328206,  0.98537945])

In [ ]:
a2.min()

-0.9426581921219525

In [ ]:
a2.max()

1.7115620380327115

In [ ]:
np.random.rand(10)

array([0.07424384, 0.48230172, 0.16408555, 0.80540863, 0.05776087,
       0.99567326, 0.53894428, 0.07034768, 0.25136415, 0.21837086])

In [ ]:
#reshape
a3=np.random.rand(12)

In [ ]:
a3

array([0.47496261, 0.56649281, 0.20230996, 0.54688991, 0.08166629,
       0.69721674, 0.49312186, 0.86484649, 0.15249249, 0.83698551,
       0.29152765, 0.03853533])

In [ ]:
type(a3)

numpy.ndarray

In [ ]:
a3.reshape((6,2))

array([[0.47496261, 0.56649281],
       [0.20230996, 0.54688991],
       [0.08166629, 0.69721674],
       [0.49312186, 0.86484649],
       [0.15249249, 0.83698551],
       [0.29152765, 0.03853533]])

In [ ]:
a3

array([0.47496261, 0.56649281, 0.20230996, 0.54688991, 0.08166629,
       0.69721674, 0.49312186, 0.86484649, 0.15249249, 0.83698551,
       0.29152765, 0.03853533])

In [ ]:
a3.reshape((2,2,3))

array([[[0.47496261, 0.56649281, 0.20230996],
        [0.54688991, 0.08166629, 0.69721674]],

       [[0.49312186, 0.86484649, 0.15249249],
        [0.83698551, 0.29152765, 0.03853533]]])

In [ ]:
a4=np.random.randint(10,20,10)

In [ ]:
a4

array([14, 16, 10, 14, 19, 12, 11, 17, 16, 12])

In [ ]:
#to show what is the index/position of smallest number
a4.argmin()

2

In [ ]:
#to show what is the index/position of biggest number
a4.argmax()

4

In [ ]:
a5=np.random.randint(10,50,(3,4))

In [ ]:
a5

array([[46, 35, 19, 34],
       [45, 12, 48, 43],
       [15, 13, 38, 36]])

In [ ]:
#to find specific value using index
a5[1,2]

48

In [ ]:
a5[2,3]

36

In [ ]:
#to print entire row
a5[1]

array([45, 12, 48, 43])

In [ ]:
#to print values from desired rows and columns in a matrix
a5[0:3,0:3]

array([[46, 35, 19],
       [45, 12, 48],
       [15, 13, 38]])

In [ ]:
#returns the position at which the condition is true
np.where(a5<13)

(array([1]), array([1]))

In [ ]:
#using where condition
np.where(a5<15,a5*2,a5)

array([[46, 35, 19, 34],
       [45, 24, 48, 43],
       [15, 26, 38, 36]])